name: gwenchana
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter 
  cupertino_icons: ^1.0.8
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  equatable: ^2.0.5
  freezed: ^3.0.4
  shared_preferences: ^2.0.6
  firebase_auth: ^5.6.1
  google_sign_in: ^6.2.1
  auto_route: ^10.1.0+1
  flutter_facebook_auth: ^7.1.2
  mockito: ^5.4.5
  flutter_dotenv: ^5.2.1
  hive: ^2.2.3
  intl: ^0.19.0
  firebase_core: ^3.15.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  bloc_test: ^10.0.0
  auto_route_generator: ^10.0.0+1
  build_runner: any


flutter:

  uses-material-design: true
  generate: true


  assets:
    - assets/images/
    - assets/logo/
    - assets/flags/
    - .env
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic