name: gwenchana
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localization: ^0.3.2 
  cupertino_icons: ^1.0.8
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  equatable: ^2.0.5
  freezed: ^3.0.4
  shared_preferences: ^2.0.6
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  google_sign_in: ^6.2.1
  go_router: ^15.1.3
  flutter_facebook_auth: ^7.1.2
  mockito: ^5.4.5
  flutter_dotenv: ^5.2.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  bloc_test: ^10.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/logo/
    - assets/flags/
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic